### PR TITLE
convert to lexd

### PR DESCRIPTION
**Pull request by mr-martian**
As discussed at https://tinodidriksen.com/pisg/OFTC/logs/#apertium/2022-03-17.log

To the best of my understanding, the lexd here is equivalent to the lexc, with the exception that I implemented full reduplication.

If any issues arise I can help try to poke it some more.

(sorry about the ugly sed lines, but lexd is somewhat opinionated about what multichar symbols are)

@reynoldsnlp

### CODE REVIEW

**Comment by snomos** [comment]
CI needs to install Apertium tools for the lexd build to go through. With the old CI using GH Actions one could specify that in the action yaml file. How can we do that in the new TaskCluster system, @Eijebong ?

**Comment by Eijebong** [comment]
3 solutions:

1) We rename the repository to `lang-hil-x-ext-apertium`. That requires rereleasing the language on pahkat under the new name and removing the old packages but would automatically be picked up as needing apertium without any other changes.
2) We add a list of languages using apertium to a list here https://github.com/divvun/taskcluster-scripts/blob/bb41ff12cde23f2fccbd1e6016b2c398562e6d29/decision_task.py#L46
3) We remove that check and install apertium in CI with every language

I would go for 2 and keep the automagic detection (i.e if the repo name ends up with apertium or if it's in a list of specified languages). Thoughts?

**Comment by snomos** [comment]
I agree with @Eijebong - solution 2 seems good. Would you do that, @Eijebong ?

**Comment by Eijebong** [comment]
This has been done, you can rebase the PR to get CI builds too.

**Comment by reynoldsnlp** [comment]
@adamsnat007 worked out a similar, but slightly different approach, inspired by this one. Thanks for the suggestion, @mr-martian !

**Pull request closed without merging**
